before_install:
  - sudo apt-get install -y autopoint libconfig-dev
addons:
  apt:
    update: true

language: c
compiler:
  - clang
  - gcc

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
